### ISSUE TITLE
Errors running deep mind control suite environments

### ISSUE THREAD

**Issue by retinfai** [UoA-CARES/gymnasium_envrionments#11]
Doing a clean install and pip install requirements results in the following errors, when running the example deep mind control suite command (this has been reproduced on multiple machines).

```
Traceback (most recent call last):
  File "/home/anyone/gymnasium_envrionments/scripts/train.py", line 90, in <module>
    main()
  File "/home/anyone/gymnasium_envrionments/scripts/train.py", line 49, in main
    env = env_factory.create_environment(env_config)  # This line should be here for seed consistency issues
  File "/home/anyone/gymnasium_envrionments/scripts/EnvironmentFactory.py", line 27, in create_environment
    env = DMCSImage(config) if config.image_observation else DMCS(config)
  File "/home/anyone/gymnasium_envrionments/scripts/envrionments/DMCS.py", line 22, in __init__
    self.env = suite.load(self.domain, self.task)
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/suite/__init__.py", line 113, in load
    return build_environment(domain_name, task_name, task_kwargs,
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/suite/__init__.py", line 148, in build_environment
    env = domain.SUITE[task_name](**task_kwargs)
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/suite/ball_in_cup.py", line 41, in catch
    physics = Physics.from_xml_string(*get_model_and_assets())
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/mujoco/engine.py", line 443, in from_xml_string
    return cls.from_model(model)
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/mujoco/engine.py", line 426, in from_model
    return cls(data)
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/mujoco/engine.py", line 123, in __init__
    self._reload_from_data(data)
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/mujoco/engine.py", line 407, in _reload_from_data
    model=index.struct_indexer(self.model, 'mjmodel', axis_indexers),
  File "/home/anyone/.local/lib/python3.10/site-packages/dm_control/mujoco/index.py", line 628, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjModel' object has no attribute 'bvh_geomid'
```

**Comment by beardyFace** [comment]
This may be related to needing to be properly swapping to gymnasium not the older gym

**Comment by qiaoting159753** [comment]
Maybe run a "pip list", and post the version of 'mujoco' and 'mujoco-py', 'dm_control' here?

**Comment by beardyFace** [comment]
I have updated the requirements to be the newer gymnasium instead of gym. Be worth testing this all from scratch again

**Comment by beardyFace** [comment]
reproduced this bug on a fresh install inside of Docker - will dig into it now I can reproduce it effectively
